id: I4E056D63
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T18:23:05+00:00'
last_modified: '2022-06-15T17:44:44.258407+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4884
  title: གསུང་འབུམ། དྲི་མེད་འོད་ཟེར། （དཔལ་བརྩེགས། མེས་པོའི་ཤུལ་བཞག）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '2692':
      image_group_id: I1KG4886
      title: Volume 1 of gsung 'bum/_dri med 'od zer
      total_pages: 392
      order: 1
      base_file: 2692.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
